### ISSUE TITLE
Unterschiedliche Standorte in der shifts view farblich auseinanderhalten (je Standort eigene bg-Farbe)

### ISSUE THREAD

**Issue by welcomehelp** [welcomehelpde/engelsystem#16]

**Comment by netrunner99** [comment]
möglicherweise sogar jeder Standort mit eigener Hintergrundfarbe

**Comment by sdvg** [comment]
Es geht um die Darstellung, die in folgendem Screenshot zu sehen ist, oder?

![screen shot 2015-10-25 at 18 54 38](https://cloud.githubusercontent.com/assets/971072/10716978/eecafc2a-7b49-11e5-8453-45a80510d277.png)

Da sehe ich noch das Problem, dass die Hintergrundfarbe bereits dynamisch ist:

```css
#shifts td.free {
  border: 1px solid #d9534f;
  background-color: #f2dede;
}
a#shifts td.free:hover,
a#shifts td.free:focus {
  background-color: #e4b9b9;
}
#shifts td.occupied {
  border: 1px solid #5cb85c;
  background-color: #dff0d8;
}
a#shifts td.occupied:hover,
a#shifts td.occupied:focus {
  background-color: #c1e2b3;
}
#shifts td.collides {
  border: 1px solid #f0ad4e;
  background-color: #fcf8e3;
}
a#shifts td.collides:hover,
a#shifts td.collides:focus {
  background-color: #f7ecb5;
}
#shifts td.own {
  border: 1px solid #777777;
}
```
Wir könnten den Farbcode aber auch auf das Label des Ortes anwenden.. das hilft nur leider nicht, die Ansicht als Ganzes übersichtlicher zu machen.

Hätte da jemand einen alternativen Vorschlag oder ein Beispiel für mich, wann die Darstellung unübersichtlich wird, damit ich mir ein besseres Bild davon machen kann?
